version: '3.9'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  consolidada:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${CONSOLIDADA_USER}'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: '${CONSOLIDADA_PASS}'
    ports:
      - '${CONSOLIDADA_PORT}:${CONSOLIDADA_PORT}'
    expose:
      - '${CONSOLIDADA_PORT}'
    command: -p ${CONSOLIDADA_PORT}
    volumes:
      - ./docker/postgres-consolidada:/var/lib/postgresql/data
      - ./${DB_SCHEMA}:/docker-entrypoint-initdb.d/01-schema.sql
      - ./${DB_DATA}:/docker-entrypoint-initdb.d/02-data.sql
      - ./constraints.sql:/docker-entrypoint-initdb.d/03-constraints.sql

  temporal:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${TEMP_USER}'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: '${TEMP_PASS}'
    ports:
      - '${TEMP_PORT}:${TEMP_PORT}'
    expose:
      - '${TEMP_PORT}'
    command: -p ${TEMP_PORT}
    volumes:
      - ./docker/postgres-temporal:/var/lib/postgresql/data
      - ./${DB_SCHEMA}:/docker-entrypoint-initdb.d/01-schema.sql
      - ./constraints.sql:/docker-entrypoint-initdb.d/02-constraints.sql

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}

  extract_service:
    build:
      context: .
      dockerfile: Dockerfile.extract
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - temporal
      - redis
    environment:
      - RABBIT_HOST=rabbitmq
      - TEMP_IP=temporal
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 2
    volumes:
      - ./docker/extract_service:/app/logs

  pendientes_service:
    build:
      context: .
      dockerfile: Dockerfile.pendientes
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - consolidada
    environment:
      - RABBIT_HOST=rabbitmq
      - CONSOLIDADA_IP=consolidada
      - PYTHONUNBUFFERED=1

  traspaso_service:
    build:
      context: .
      dockerfile: Dockerfile.traspaso
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - temporal
      - consolidada
    environment:
      - RABBIT_HOST=rabbitmq
      - TEMP_IP=temporal
      - CONSOLIDADA_IP=consolidada
      - PYTHONUNBUFFERED=1
    volumes:
      - ./docker/trapaso_service:/app/logs

volumes:
  db:
  data:
    external: true
  rabbitmq:
  postgres:
  postgres-temporal:
  pgadmin-data:


