version: '3.9'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - extract

  consolidada:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${CONSOLIDADA_USER}'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: '${CONSOLIDADA_PASS}'
      SCHEMA: '${SCHEMA_CONSOLIDADA}'
    ports:
      - '${CONSOLIDADA_PORT}:5400'
    expose:
      - '5400'
    command: -p 5400
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      - ./docker/data:/app
      - ./${SCHEMA_CONSOLIDADA}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - check

  temporal:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${TEMP_USER}'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: '${TEMP_PASS}'
    ports:
      - '${TEMP_PORT}:5411'
    expose:
      - '5411'
    command: -p 5411
    volumes:
      - ./docker/postgres-temporal:/var/lib/postgresql/data
      - ./docker/data:/app
      - ./${SCHEMA_TEMP}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - extract

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - extract

  extract_service:
    build:
      context: .
      dockerfile: Dockerfile.extract
    env_file:
      - .env
    deploy:
      replicas: 2
    networks:
      - extract

  check_queue:
    build:
      context: .
      dockerfile: Dockerfile.check
    env_file:
      - .env
    networks:
      - check

volumes:
  db:
  data:
    external: true
  rabbitmq:
  postgres:
  postgres-temporal:
  pgadmin-data:


networks:
  extract:
  check:
