version: '3.8'
services:

  consolidada:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'ghtorrent'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: 'vps228.2o22'
    ports:
      - '5432:5400'
    expose:
      - '5400'
    command: -p 5400
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./data:/app
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  temporal:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'ghtorrent'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: 'vps228.2o22'
    ports:
      - '6611:5411'
    expose:
      - '5411'
    command: -p 5411
    volumes:
      - ./postgres-temporal:/var/lib/postgresql/data
      - ./data:/app
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  metabase-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'metabase'
      POSTGRES_DB: 'metabase'
      POSTGRES_PASSWORD: 'vps228.2o22'
    ports:
      - '6606:5432'
    expose:
      - '5432'
    volumes:
      - ./metabase-db:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 8080:3000
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: vps228.2o22
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db
    links:
      - metabase-db

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  db:
  data:
    external: true
  rabbitmq:
  metabase-data:
  postgres:
  postgres-temporal:
