version: '3.8'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  consolidada:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${CONSOLIDADA_USER}'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: '${CONSOLIDADA_PASS}'
      SCHEMA: '${SCHEMA_CONSOLIDADA}'
    ports:
      - '${CONSOLIDADA_PORT}:${CONSOLIDADA_PORT}'
    expose:
      - '${CONSOLIDADA_PORT}'
    command: -p ${CONSOLIDADA_PORT}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      - ./docker/data:/app
      - ./${SCHEMA_CONSOLIDADA}:/docker-entrypoint-initdb.d/init.sql

  temporal:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${TEMP_USER}'
      POSTGRES_DB: 'ghtorrent'
      POSTGRES_PASSWORD: '${TEMP_PASS}'
    ports:
      - '${TEMP_PORT}:${TEMP_PORT}'
    expose:
      - '${TEMP_PORT}'
    command: -p ${TEMP_PORT}
    volumes:
      - ./docker/postgres-temporal:/var/lib/postgresql/data
      - ./docker/data:/app
      - ./${SCHEMA_TEMP}:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}

  extract_service:
    image: ghcr.io/matiasbarram/repoinsights-extract-service:staging
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - temporal
      - redis
    environment:
      - RABBIT_HOST=rabbitmq
      - TEMP_IP=temporal
      - REDIS_HOST=redis
    deploy:
      replicas: 2

  check_queue:
    image: ghcr.io/matiasbarram/repoinsights-pendientes-service:staging
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - consolidada
    environment:
      - RABBIT_HOST=rabbitmq
      - CONSOLIDADA_IP=consolidada

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 8080:3000
    volumes:
      - ./docker/metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: vps228.2o22
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db
    links:
      - metabase-db
  metabase-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'metabase'
      POSTGRES_DB: 'metabase'
      POSTGRES_PASSWORD: 'vps228.2o22'
    ports:
      - '6606:5432'
    expose:
      - '5432'
    volumes:
      - ./docker/metabase-db:/var/lib/postgresql/data

volumes:
  db:
  data:
    external: true
  rabbitmq:
  metabase-data:
  postgres:
  postgres-temporal:
