name: Build
on:
  push:
    branches:
      - develop
      - staging
      - production
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [extract_service, metrics_service, modificacion_service, pendientes_service, traspaso_service]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./services/${{ matrix.service }}
